theme: jekyll-theme-slate
title: SCANeR Quick Starts
description : Resources for SCANeR users
show_downloads: true
plugins:
  - jemoji
github:
  repository_url: https://github.com/AVSimulation/SCANeR-Quick-Starts/tree/Published
  zip_url: https://stockage.scanersimulation.com/Evaluation/2021/Samples-Pack-2021.2r2.zip
  youtube_url: https://www.youtube.com/channel/UCYNNe9SaA3LjCFb2qXmhkoA
